/**
 * HubSpot API Integration — Partner Portal
 * Creates ONE deal per submission in Elevate pipeline, associates contact,
 * pins a structured note with ALL site details, assigns ELEV-ID reference.
 */

import type { Site, Requirements, UrgencyLevel } from '@/types';
import {
  BUILDING_TYPE_LABELS,
  CONNECTIVITY_NEED_LABELS,
  URGENCY_LABELS,
  YES_NO_LABELS,
} from '@/types';

const HUBSPOT_API_KEY = import.meta.env.VITE_HUBSPOT_API_KEY;
const BASE_URL = 'https://api.hubapi.com';

// Elevate Pipeline — hard-coded from HubSpot config
const ELEVATE_PIPELINE_ID = '883283306';
const NEW_ENQUIRY_STAGE_ID = '1326716345'; // First stage in Elevate pipeline

export class HubSpotError extends Error {
  constructor(
    message: string,
    public statusCode?: number,
    public response?: any,
  ) {
    super(message);
    this.name = 'HubSpotError';
  }
}

// ── Retry Logic ─────────────────────────────────────────────────

async function fetchWithRetry(
  url: string,
  options: RequestInit,
  maxRetries = 3,
): Promise<Response> {
  let lastError: Error | null = null;

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      const response = await fetch(url, options);

      if (response.status >= 400 && response.status < 500) return response;

      if (!response.ok && attempt < maxRetries - 1) {
        await new Promise((r) => setTimeout(r, Math.pow(2, attempt) * 1000));
        continue;
      }

      return response;
    } catch (error) {
      lastError = error as Error;
      if (attempt < maxRetries - 1) {
        await new Promise((r) => setTimeout(r, Math.pow(2, attempt) * 1000));
      }
    }
  }

  throw lastError || new Error('Max retries exceeded');
}

function headers(): Record<string, string> {
  return {
    Authorization: `Bearer ${HUBSPOT_API_KEY}`,
    'Content-Type': 'application/json',
  };
}

// ── Contact Lookup / Create ─────────────────────────────────────

export async function findOrCreateContact(
  name: string,
  email: string,
): Promise<string> {
  if (!HUBSPOT_API_KEY) throw new HubSpotError('HubSpot API key not configured');

  // Search for existing contact by email
  const searchRes = await fetchWithRetry(`${BASE_URL}/crm/v3/objects/contacts/search`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({
      filterGroups: [
        {
          filters: [
            { propertyName: 'email', operator: 'EQ', value: email },
          ],
        },
      ],
      properties: ['email', 'firstname', 'lastname'],
      limit: 1,
    }),
  });

  if (searchRes.ok) {
    const searchData = await searchRes.json();
    if (searchData.total > 0) {
      return searchData.results[0].id;
    }
  }

  // Not found — create new contact
  const [firstName, ...lastParts] = name.split(' ');
  const lastName = lastParts.join(' ') || '';

  const createRes = await fetchWithRetry(`${BASE_URL}/crm/v3/objects/contacts`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({
      properties: {
        email,
        firstname: firstName,
        lastname: lastName,
      },
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json();
    throw new HubSpotError(`Failed to create contact: ${createRes.statusText}`, createRes.status, err);
  }

  const contactData = await createRes.json();
  return contactData.id;
}

// ── Deal Creation ───────────────────────────────────────────────

/**
 * Creates a SINGLE deal for the entire opportunity.
 * elevateRef is the ELEV-IDXXXXX reference generated by the portal.
 */
export async function createDeal(
  companyName: string,
  urgency: UrgencyLevel,
  elevateRef: string,
  siteCount?: number,
  accountRef?: string,
): Promise<string> {
  if (!HUBSPOT_API_KEY) throw new HubSpotError('HubSpot API key not configured');

  const properties: Record<string, string> = {
    dealname: companyName,
    pipeline: ELEVATE_PIPELINE_ID,
    elevate_ref: elevateRef,
  };

  // Only set stage if we have the ID
  if (NEW_ENQUIRY_STAGE_ID) {
    properties.dealstage = NEW_ENQUIRY_STAGE_ID;
  }

  // Key properties — these are the ones worth having as deal-level fields
  // Everything else goes in the structured note
  if (siteCount !== undefined) {
    properties.site_count = String(siteCount);
  }
  if (accountRef) {
    properties.customer_account_reference = accountRef;
  }

  const res = await fetchWithRetry(`${BASE_URL}/crm/v3/objects/deals`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({ properties }),
  });

  if (!res.ok) {
    const err = await res.json();
    throw new HubSpotError(`Failed to create deal: ${res.statusText}`, res.status, err);
  }

  const dealData = await res.json();
  return dealData.id;
}

// ── Association ─────────────────────────────────────────────────

export async function associateDealToContact(
  dealId: string,
  contactId: string,
): Promise<void> {
  if (!HUBSPOT_API_KEY) return;

  const res = await fetchWithRetry(
    `${BASE_URL}/crm/v3/objects/deals/${dealId}/associations/contacts/${contactId}/deal_to_contact`,
    {
      method: 'PUT',
      headers: headers(),
    },
  );

  if (!res.ok) {
    console.warn(`Failed to associate deal ${dealId} to contact ${contactId}`);
  }
}

// ── Note Creation ───────────────────────────────────────────────

/**
 * Builds a single structured note containing ALL sites and full submission data.
 * One note per deal — not one per site.
 */
export function buildStructuredNote(
  elevateRef: string,
  agentName: string,
  agentEmail: string,
  companyName: string,
  accountRef: string,
  sites: Site[],
  requirements: Requirements,
  urgency: UrgencyLevel,
  additionalNotes: string,
): string {
  const lines: string[] = [
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    'ELEVATE OPPORTUNITY SUBMISSION',
    `Reference: ${elevateRef}`,
    `Submitted: ${new Date().toLocaleString('en-GB')}`,
    `Agent: ${agentName} (${agentEmail})`,
    '',
    '── END USER ─────────────────────────────',
    `Name: ${companyName}`,
    `Account Ref: ${accountRef || 'Not provided'}`,
    `Sites: ${sites.length}`,
  ];

  // ── ALL SITES ───────────────────────────────────────────────
  sites.forEach((site, i) => {
    lines.push(
      '',
      `── SITE ${i + 1}: ${site.site_name} ${'─'.repeat(Math.max(1, 30 - site.site_name.length))}`,
      `Address: ${site.site_address}`,
      `Coordinates: ${site.site_coordinates || 'Not provided'}`,
      `Building Type: ${BUILDING_TYPE_LABELS[site.building_type]}`,
      `Buildings to Connect: ${site.buildings_to_connect}`,
    );
  });

  // ── REQUIREMENTS ────────────────────────────────────────────
  lines.push(
    '',
    '── REQUIREMENTS ─────────────────────────',
    `Solution Type: ${requirements.solution_type === 'permanent' ? 'Permanent' : 'Temporary'}`,
  );

  if (requirements.solution_type === 'temporary' && requirements.temp_duration) {
    lines.push(`Duration: ${requirements.temp_duration}`);
  }

  lines.push(
    `Users at Location: ${requirements.users_at_location || 'Not specified'}`,
    `Connectivity Need: ${CONNECTIVITY_NEED_LABELS[requirements.connectivity_need]}`,
    `Static IP Required: ${YES_NO_LABELS[requirements.static_ip_required]}`,
    `Existing Connectivity: ${requirements.existing_connectivity || 'None specified'}`,
    `WiFi Coverage Needed: ${YES_NO_LABELS[requirements.wifi_needed]}`,
  );

  if (requirements.other_requirements) {
    lines.push(`Other Requirements: ${requirements.other_requirements}`);
  }

  // ── URGENCY ─────────────────────────────────────────────────
  lines.push(
    '',
    `── URGENCY: ${URGENCY_LABELS[urgency]} ──`,
  );

  // ── NOTES ───────────────────────────────────────────────────
  if (additionalNotes) {
    lines.push(
      '',
      '── ADDITIONAL NOTES ─────────────────────',
      additionalNotes,
    );
  }

  lines.push(
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
  );

  return lines.join('\n');
}

export async function createNoteOnDeal(
  dealId: string,
  noteBody: string,
): Promise<string> {
  if (!HUBSPOT_API_KEY) throw new HubSpotError('HubSpot API key not configured');

  // Create the note
  const noteRes = await fetchWithRetry(`${BASE_URL}/crm/v3/objects/notes`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({
      properties: {
        hs_note_body: noteBody,
      },
    }),
  });

  if (!noteRes.ok) {
    const err = await noteRes.json();
    throw new HubSpotError(`Failed to create note: ${noteRes.statusText}`, noteRes.status, err);
  }

  const noteData = await noteRes.json();
  const noteId = noteData.id;

  // Associate note with deal
  const assocRes = await fetchWithRetry(
    `${BASE_URL}/crm/v3/objects/notes/${noteId}/associations/deals/${dealId}/note_to_deal`,
    {
      method: 'PUT',
      headers: headers(),
    },
  );

  if (!assocRes.ok) {
    console.warn(`Failed to associate note ${noteId} to deal ${dealId}`);
  }

  return noteId;
}

// ── Full Submission Orchestrator ────────────────────────────────

export interface SubmissionResult {
  dealId: string;
  elevateRef: string;
  contactId: string;
  errors: string[];
}

/**
 * Single orchestrator — creates ONE deal, ONE note, associates ONE contact.
 * elevateRef is pre-generated by the caller (from Supabase sequence).
 */
export async function submitOpportunity(
  elevateRef: string,
  agentName: string,
  agentEmail: string,
  companyName: string,
  accountRef: string,
  sites: Site[],
  requirements: Requirements,
  urgency: UrgencyLevel,
  additionalNotes: string,
): Promise<SubmissionResult> {
  const result: SubmissionResult = {
    dealId: '',
    elevateRef,
    contactId: '',
    errors: [],
  };

  // Step 1: Find or create agent contact
  try {
    result.contactId = await findOrCreateContact(agentName, agentEmail);
  } catch (err) {
    result.errors.push(`Contact creation failed: ${err instanceof Error ? err.message : 'Unknown'}`);
  }

  // Step 2: Create ONE deal for the whole opportunity
  try {
    result.dealId = await createDeal(companyName, urgency, elevateRef, sites.length, accountRef);
  } catch (err) {
    result.errors.push(`Deal creation failed: ${err instanceof Error ? err.message : 'Unknown'}`);
    return result; // Can't continue without a deal
  }

  // Step 3: Associate deal with contact
  if (result.contactId) {
    try {
      await associateDealToContact(result.dealId, result.contactId);
    } catch (err) {
      result.errors.push(`Association failed: ${err instanceof Error ? err.message : 'Unknown'}`);
    }
  }

  // Step 4: Create single structured note with ALL sites
  try {
    const noteBody = buildStructuredNote(
      elevateRef,
      agentName,
      agentEmail,
      companyName,
      accountRef,
      sites,
      requirements,
      urgency,
      additionalNotes,
    );
    await createNoteOnDeal(result.dealId, noteBody);
  } catch (err) {
    result.errors.push(`Note creation failed: ${err instanceof Error ? err.message : 'Unknown'}`);
  }

  return result;
}
